spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    database: mysql
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/poko-local
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver